### ISSUE TITLE
Make core-weekly-generator resilient to unknown branches

### ISSUE THREAD

**Issue by matks** [PrestaShop/core-weekly-generator#108]
```
Run cd ~/core-weekly-generator && python core-weekly.py --week 47 > $GITHUB_WORKSPACE/news/_posts/core-weekly/$(date +"%Y-%m-%d-coreweekly-47-%Y.md")
Traceback (most recent call last):
  File "core-weekly.py", line 36, in <module>
    main()
  File "core-weekly.py", line 30, in main
    print(core_weekly.generate())
  File "/home/runner/core-weekly-generator/core_weekly/core_weekly.py", line 98, in generate
    content += self.template.build_merged_pull_requests(merged_pull_requests)
  File "/home/runner/core-weekly-generator/core_weekly/template.py", line 315, in build_merged_pull_requests
    self.verify_no_unknown_branch(grouped_core_items, CORE_BRANCHES)
  File "/home/runner/core-weekly-generator/core_weekly/template.py", line 295, in verify_no_unknown_branch
    raise Exception('Cannot find branch "{}" in configured branches'.format(key))
Exception: Cannot find branch "1.7.8.2-build" in configured branches
```

The generator should ignore unknown branches instead of crashing

**Comment by matks** [comment]
```
python3 core-weekly.py --week 1
Traceback (most recent call last):
  File "core-weekly.py", line 36, in <module>
    main()
  File "core-weekly.py", line 30, in main
    print(core_weekly.generate())
  File "/Users/mFerment/www/prestashop/core-weekly-generator/core_weekly/core_weekly.py", line 98, in generate
    content += self.template.build_merged_pull_requests(merged_pull_requests)
  File "/Users/mFerment/www/prestashop/core-weekly-generator/core_weekly/template.py", line 315, in build_merged_pull_requests
    self.verify_no_unknown_branch(grouped_core_items, CORE_BRANCHES)
  File "/Users/mFerment/www/prestashop/core-weekly-generator/core_weekly/template.py", line 295, in verify_no_unknown_branch
    raise Exception('Cannot find branch "{}" in configured branches'.format(key))
Exception: Cannot find branch "develop / 1.7.8.x" in configured branches
```
