### ISSUE TITLE
Syntax error when trying to generate a core-weeklyè

### ISSUE THREAD

**Issue by ttoine** [PrestaShop/core-weekly-generator#14]
Hello,

I tried the core-weekly generator this morning and I get this error:

```
$ ./core-weekly.py --week 40
Traceback (most recent call last):
  File "./core-weekly.py", line 4, in <module>
    from core_weekly import CoreWeekly
  File "/home/ttoine/Documents/Prestashop/core weekly/core-weekly-generator/core_weekly/__init__.py", line 2, in <module>
    from .core_weekly import CoreWeekly
  File "/home/ttoine/Documents/Prestashop/core weekly/core-weekly-generator/core_weekly/core_weekly.py", line 51
    first_day = datetime.datetime.strptime(f'{year}-W{int(week )- 1}-1', "%Y-W%W-%w").date()
                                                                      ^
SyntaxError: invalid syntax
```

My version of python:

```
$ python --version
Python 3.6.8
```

Of course, I did the prerequisites to install the dependencies.

**Comment by PierreRambaud** [comment]
I'm not able to reproduce
```bash
$ python --version
Python 3.6.8
[3.6.8] got@got:~/projects/prestashop/core-weekly-generator[master]$ ./core-weekly.py --week 40 
---
layout: post
title:  "PrestaShop Core Weekly - Week XXXX of 2019"
subtitle: "An inside look at the PrestaShop codebase"
date:   XXXX
...
```

Could you run `/usr/bin/env python --version` ?

Could you run the script

**Comment by ttoine** [comment]
```
$ /usr/bin/env python --version
Python 2.7.15+
```
ok so why is that different from `python --version` ???

**Comment by PierreRambaud** [comment]
Because of how you manage your default environment tools.
I commit https://github.com/PrestaShop/core-weekly-generator/commit/162c960d3d3b4c7039daac8583b2c831aff37180 which will force to run python3 instead.

**Comment by ttoine** [comment]
your commit solved the issue, thanks a lot.
