### ISSUE TITLE
Cannot use newest version

### ISSUE THREAD

**Issue by matks** [PrestaShop/core-weekly-generator#16]
```
$ ./core-weekly.py --help
Traceback (most recent call last):
  File "./core-weekly.py", line 4, in <module>
    from core_weekly import CoreWeekly
  File "/Users/mFerment/www/prestashop/core-weekly-generator/core_weekly/__init__.py", line 2, in <module>
    from .core_weekly import CoreWeekly
  File "/Users/mFerment/www/prestashop/core-weekly-generator/core_weekly/core_weekly.py", line 3, in <module>
    from .report import Report
  File "/Users/mFerment/www/prestashop/core-weekly-generator/core_weekly/report.py", line 1, in <module>
    from .github import GitHub
  File "/Users/mFerment/www/prestashop/core-weekly-generator/core_weekly/github.py", line 3, in <module>
    import requests_cache
ModuleNotFoundError: No module named 'requests_cache'
```

Happens to me with both python2 and python3, although I have installed pip dependencies 🤔

**Comment by Progi1984** [comment]
@matks You need Python 3.4+.

**Comment by matks** [comment]
I'm using python 3.7.4

**Comment by PierreRambaud** [comment]
Did you try to install dependencies?
`pip install -r requirements.txt`?

**Comment by matks** [comment]
Fixed, I messed up pip between python2 and python3
